---
- hosts: all
  user: root 
  tasks:
  - name: Append user homeboy1 to Existing group
    user:
      name: homeboy1
      groups: "root, docker, test"
	  state: present
      append: yes
	  
  - name: Append user homeboy1 to Existing group
    user:
      name: homeboy2
      groups: "root, docker, test"
	  state: present
      append: yes 